[build]
  command = "yarn build"
  publish = ".output/public"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
  force = false

[functions]
  directory = ".output/server"
  node_bundler = "esbuild"
  external_node_modules = ["@google-analytics/data"]

[build.environment]
  NODE_VERSION = "20"
